export async function seedDefaultData(prisma, organizationId) {
  const behaviors = [
    // Attendance
    {
      name: "Signed in today",
      description: "Youth showed up and signed in",
      minPoints: 1,
      maxPoints: 1,
      isDefault: true,
      category: "Attendance",
    },

    // Academic
    {
      name: "Completed homework / Power Hour",
      description:
        "Youth completed their homework or participated in Power Hour",
      minPoints: 3,
      maxPoints: 10,
      isDefault: true,
      category: "Academic",
    },
    {
      name: "Turned in a completed assignment",
      description: "Youth submitted a finished assignment",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Academic",
    },
    {
      name: "Asked for help",
      description: "Youth demonstrated self-advocacy by asking for assistance",
      minPoints: 3,
      maxPoints: 5,
      isDefault: true,
      category: "Academic",
    },
    {
      name: "Helped a peer with homework",
      description: "Youth supported another member with their schoolwork",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Academic",
    },
    {
      name: "Read independently during reading time",
      description: "Youth read on their own during structured reading time",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Academic",
    },
    {
      name: "Finished a book",
      description: "Youth completed reading an entire book",
      minPoints: 5,
      maxPoints: 15,
      isDefault: true,
      category: "Academic",
    },

    // Participation
    {
      name: "Participated in an activity",
      description: "Youth actively engaged in a program activity",
      minPoints: 3,
      maxPoints: 10,
      isDefault: true,
      category: "Participation",
    },
    {
      name: "Stayed engaged for the full session",
      description: "Youth remained focused and present throughout the program",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Participation",
    },
    {
      name: "Tried something new",
      description:
        "Youth stepped outside their comfort zone and attempted something unfamiliar",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Participation",
    },
    {
      name: "Raised their hand to contribute",
      description:
        "Youth volunteered to answer a question or share with the group",
      minPoints: 3,
      maxPoints: 5,
      isDefault: true,
      category: "Participation",
    },
    {
      name: "Shared an idea with the group",
      description:
        "Youth contributed a thought or suggestion to a group discussion",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Participation",
    },

    // Helping Others
    {
      name: "Helped a staff member",
      description: "Youth voluntarily assisted a staff member",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Helping Others",
    },
    {
      name: "Helped a peer",
      description: "Youth supported another member in any way",
      minPoints: 3,
      maxPoints: 10,
      isDefault: true,
      category: "Helping Others",
    },
    {
      name: "Helped set up or clean up for an event",
      description: "Youth assisted with event preparation or cleanup",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Helping Others",
    },
    {
      name: "Helped with snack, lunch, or dinner",
      description: "Youth assisted with food preparation or distribution",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Helping Others",
    },
    {
      name: "Shared supplies with someone",
      description:
        "Youth shared their materials with another member who needed them",
      minPoints: 3,
      maxPoints: 5,
      isDefault: true,
      category: "Helping Others",
    },

    // Character
    {
      name: "Welcomed a new member",
      description: "Youth made a new person feel included and comfortable",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Character",
    },
    {
      name: "Complimented someone sincerely",
      description:
        "Youth offered a genuine compliment to a peer or staff member",
      minPoints: 3,
      maxPoints: 5,
      isDefault: true,
      category: "Character",
    },
    {
      name: "Apologized sincerely",
      description: "Youth offered a genuine apology for something they did",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Character",
    },
    {
      name: "Walked away from an argument",
      description:
        "Youth chose to remove themselves from a conflict rather than escalate",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Character",
    },
    {
      name: "Resolved a conflict peacefully",
      description: "Youth handled a disagreement calmly and respectfully",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Character",
    },
    {
      name: "Took responsibility for a mistake",
      description: "Youth owned up to something they did wrong",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Character",
    },

    // Leadership
    {
      name: "Mentored a younger member",
      description: "Youth guided or supported a younger peer",
      minPoints: 5,
      maxPoints: 15,
      isDefault: true,
      category: "Leadership",
    },
    {
      name: "Led a group activity",
      description: "Youth took initiative and led others in an activity",
      minPoints: 5,
      maxPoints: 15,
      isDefault: true,
      category: "Leadership",
    },
    {
      name: "Kept the group focused and on task",
      description:
        "Youth helped maintain focus during a group activity or session",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Leadership",
    },
    {
      name: "Read to a younger member",
      description: "Youth read aloud to a younger peer",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Leadership",
    },

    // Cleaning & Facility Care
    {
      name: "Picked up trash",
      description: "Youth picked up litter inside or outside the facility",
      minPoints: 3,
      maxPoints: 5,
      isDefault: true,
      category: "Cleaning & Facility Care",
    },
    {
      name: "Swept a room",
      description: "Youth swept a common area or program room",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Cleaning & Facility Care",
    },
    {
      name: "Wiped down tables",
      description: "Youth cleaned tables in a common area or program room",
      minPoints: 3,
      maxPoints: 5,
      isDefault: true,
      category: "Cleaning & Facility Care",
    },
    {
      name: "Vacuumed the carpet",
      description: "Youth vacuumed a carpeted area",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Cleaning & Facility Care",
    },
    {
      name: "Cleaned windows",
      description: "Youth cleaned windows or glass surfaces",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Cleaning & Facility Care",
    },
    {
      name: "Cleaned walls",
      description: "Youth wiped down or cleaned walls",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Cleaning & Facility Care",
    },
    {
      name: "Picked up after themselves",
      description: "Youth cleaned up their own mess without being asked",
      minPoints: 3,
      maxPoints: 5,
      isDefault: true,
      category: "Cleaning & Facility Care",
    },

    // Community & Citizenship
    {
      name: "Held the door for someone",
      description: "Youth showed courtesy by holding the door open",
      minPoints: 1,
      maxPoints: 3,
      isDefault: true,
      category: "Community & Citizenship",
    },
    {
      name: "Said please and thank you unprompted",
      description: "Youth demonstrated courtesy without being reminded",
      minPoints: 1,
      maxPoints: 3,
      isDefault: true,
      category: "Community & Citizenship",
    },
    {
      name: "Behaved on the bus",
      description: "Youth demonstrated good behavior during bus transportation",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Community & Citizenship",
    },
    {
      name: "Behaved on a field trip",
      description:
        "Youth represented the club positively during an off-site activity",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Community & Citizenship",
    },
    {
      name: "Represented the club positively",
      description:
        "Youth acted as a positive ambassador for the club in the community",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Community & Citizenship",
    },

    // Athletics & Physical Activity
    {
      name: "Participated in physical activity",
      description: "Youth engaged in a physical activity or sport",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Athletics & Physical Activity",
    },
    {
      name: "Showed good sportsmanship",
      description:
        "Youth demonstrated fair play and respect during a game or activity",
      minPoints: 3,
      maxPoints: 10,
      isDefault: true,
      category: "Athletics & Physical Activity",
    },
    {
      name: "Encouraged a teammate",
      description: "Youth cheered on or motivated a fellow participant",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Athletics & Physical Activity",
    },

    // Arts & Creativity
    {
      name: "Completed an art project",
      description: "Youth finished a creative art project",
      minPoints: 3,
      maxPoints: 10,
      isDefault: true,
      category: "Arts & Creativity",
    },
    {
      name: "Shared their creative work with the group",
      description: "Youth presented or displayed their creative work to others",
      minPoints: 3,
      maxPoints: 8,
      isDefault: true,
      category: "Arts & Creativity",
    },
    {
      name: "Presented a project to the group",
      description: "Youth formally presented their work to staff or peers",
      minPoints: 5,
      maxPoints: 15,
      isDefault: true,
      category: "Arts & Creativity",
    },

    // Tech & STEM
    {
      name: "Completed a coding or STEM challenge",
      description: "Youth finished a coding exercise or STEM activity",
      minPoints: 5,
      maxPoints: 15,
      isDefault: true,
      category: "Tech & STEM",
    },
    {
      name: "Helped a peer troubleshoot",
      description:
        "Youth assisted another member in solving a technical problem",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Tech & STEM",
    },
    {
      name: "Learned a new tech skill",
      description:
        "Youth acquired a new technical skill during a program session",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Tech & STEM",
    },
    {
      name: "Demonstrated a project to the group",
      description: "Youth showed their tech or STEM project to staff or peers",
      minPoints: 5,
      maxPoints: 15,
      isDefault: true,
      category: "Tech & STEM",
    },

    // Personal Growth
    {
      name: "Kept trying after failing",
      description:
        "Youth persisted through difficulty and kept making an effort",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Personal Growth",
    },
    {
      name: "Improved on a previous attempt",
      description: "Youth showed growth by doing better than before",
      minPoints: 5,
      maxPoints: 10,
      isDefault: true,
      category: "Personal Growth",
    },
    {
      name: "Got an A on a test or assignment",
      description: "Youth achieved an A grade on a school test or assignment",
      minPoints: 5,
      maxPoints: 15,
      isDefault: true,
      category: "Personal Growth",
    },
  ];

  const prizes = [
    // Small / Instant
    {
      name: "Wooden pencil",
      pointCost: 15,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Eraser", pointCost: 15, quantity: 999, requiresAdmin: false },
    { name: "Stickers", pointCost: 15, quantity: 999, requiresAdmin: false },
    { name: "Glue", pointCost: 15, quantity: 999, requiresAdmin: false },
    {
      name: "Snack of choice",
      pointCost: 20,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Tier 1 Prize",
      description: "Staff selects from available Tier 1 items",
      pointCost: 20,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Can of soda", pointCost: 20, quantity: 999, requiresAdmin: false },
    { name: "Slime", pointCost: 25, quantity: 999, requiresAdmin: false },
    { name: "Yo-yo", pointCost: 25, quantity: 999, requiresAdmin: false },
    { name: "Hacky sack", pointCost: 25, quantity: 999, requiresAdmin: false },
    {
      name: "Jump rope (basic)",
      pointCost: 25,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Silly string",
      pointCost: 25,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Origami kit", pointCost: 30, quantity: 999, requiresAdmin: false },
    { name: "Lanyard", pointCost: 30, quantity: 999, requiresAdmin: false },
    {
      name: "Laptop sticker pack",
      pointCost: 30,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Graphite pencils",
      pointCost: 30,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Homework pass (one day)",
      pointCost: 30,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Deck of cards",
      pointCost: 35,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Coloring book",
      pointCost: 35,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Origami paper pack",
      pointCost: 35,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Hula hoop", pointCost: 35, quantity: 999, requiresAdmin: false },
    {
      name: "New scissors",
      pointCost: 35,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Journal", pointCost: 40, quantity: 999, requiresAdmin: false },
    {
      name: "Comic book / Manga volume",
      pointCost: 40,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Small toy",
      description: "Doll, action figure, or similar small toy",
      pointCost: 40,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Frisbee", pointCost: 40, quantity: 999, requiresAdmin: false },
    { name: "Fanny pack", pointCost: 45, quantity: 999, requiresAdmin: false },
    { name: "Sunglasses", pointCost: 45, quantity: 999, requiresAdmin: false },
    {
      name: "Baseball cap",
      pointCost: 50,
      quantity: 999,
      requiresAdmin: false,
    },

    // Privileges / Experiences
    {
      name: "Line leader for a week",
      pointCost: 25,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "First in line for a week",
      pointCost: 25,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Sit anywhere day",
      pointCost: 25,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Extra screen time (30 mins)",
      pointCost: 30,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Pick your seat for a week",
      pointCost: 30,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Choice of class or group game",
      pointCost: 35,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Skip chore rotation (one time)",
      pointCost: 35,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Choose the playlist for the day",
      pointCost: 35,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Front desk helper for one hour",
      pointCost: 40,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Be the DJ for one hour",
      pointCost: 40,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Extra recess or free play time",
      pointCost: 40,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Computer lab free time (30 mins)",
      pointCost: 40,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Name a club activity",
      pointCost: 45,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Lead a group activity",
      pointCost: 45,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Facility pass",
      description:
        "Game room, gym, soccer field, or teen center — youth's choice",
      pointCost: 50,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Open gym session",
      pointCost: 50,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Choose the movie for movie day",
      pointCost: 50,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Get out of homework pass (one day)",
      pointCost: 50,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Be a junior staff helper for a day",
      pointCost: 60,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Pizza party (individual)",
      pointCost: 100,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Lunch with the director",
      pointCost: 110,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Early dismissal pass",
      pointCost: 175,
      quantity: 999,
      requiresAdmin: true,
    },
    { name: "Field trip", pointCost: 200, quantity: 999, requiresAdmin: true },

    // Art & School Supplies
    { name: "New markers", pointCost: 50, quantity: 999, requiresAdmin: false },
    {
      name: "Colored pencils",
      pointCost: 50,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Maracas", pointCost: 50, quantity: 999, requiresAdmin: false },
    {
      name: "Puzzle (100-500 pieces)",
      pointCost: 50,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Kite", pointCost: 50, quantity: 999, requiresAdmin: false },
    { name: "Sketchbook", pointCost: 60, quantity: 999, requiresAdmin: false },
    {
      name: "Novel of choice",
      pointCost: 60,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Paint set", pointCost: 75, quantity: 999, requiresAdmin: false },
    { name: "Clay kit", pointCost: 75, quantity: 999, requiresAdmin: false },
    {
      name: "Craft supply kit",
      description: "Assorted craft supplies",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Watercolor set",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Calligraphy set",
      pointCost: 100,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Board game", pointCost: 125, quantity: 999, requiresAdmin: false },
    {
      name: "Lego set (small)",
      pointCost: 125,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "D&D starter kit",
      pointCost: 150,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Ukulele", pointCost: 200, quantity: 999, requiresAdmin: true },

    // Clothing & Accessories
    {
      name: "Water bottle",
      pointCost: 60,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Club apparel",
      description: "T-shirt, shorts, or other club clothing",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Drawstring backpack",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Hoodie", pointCost: 150, quantity: 999, requiresAdmin: false },
    {
      name: "Nice backpack",
      pointCost: 200,
      quantity: 999,
      requiresAdmin: true,
    },
    { name: "New shoes", pointCost: 250, quantity: 999, requiresAdmin: true },

    // Toys & Games
    {
      name: "Mini chess board",
      pointCost: 60,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Deck of Pokemon cards",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Model kit",
      description: "Car, airplane, or similar model",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Jump rope (speed)",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Nice chess board",
      pointCost: 150,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Remote control car",
      pointCost: 200,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Lego set (large)",
      pointCost: 300,
      quantity: 999,
      requiresAdmin: true,
    },

    // Sports & Outdoors
    {
      name: "Badminton set",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Resistance bands set",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Sports ball of choice",
      description: "Football, soccer ball, basketball, or volleyball",
      pointCost: 125,
      quantity: 999,
      requiresAdmin: false,
    },
    { name: "Skateboard", pointCost: 250, quantity: 999, requiresAdmin: true },
    {
      name: "Mountain bike",
      pointCost: 1000,
      quantity: 1,
      requiresAdmin: true,
    },

    // Tech
    {
      name: "Tech accessory",
      description: "USB drive, adapter, charger, or mouse pad",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Bluetooth receiver",
      pointCost: 100,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Gaming mouse",
      pointCost: 150,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Bluetooth speaker",
      pointCost: 250,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "First Act guitar",
      pointCost: 250,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Arduino starter kit",
      pointCost: 350,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Xbox controller",
      pointCost: 350,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Electronic drum pad",
      pointCost: 350,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "PS5 controller",
      pointCost: 400,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Raspberry Pi kit",
      pointCost: 400,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Airpods / earbuds",
      pointCost: 500,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Record player",
      pointCost: 500,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Electric guitar (full size)",
      pointCost: 600,
      quantity: 1,
      requiresAdmin: true,
    },

    // Big Ticket
    {
      name: "Gift card ($10)",
      pointCost: 100,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Gift card ($25)",
      pointCost: 225,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Gift card ($50)",
      pointCost: 400,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Tier 2 Prize",
      description: "Staff selects from available Tier 2 items",
      pointCost: 75,
      quantity: 999,
      requiresAdmin: false,
    },
    {
      name: "Tier 3 Prize",
      description: "Staff selects from available Tier 3 items",
      pointCost: 250,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Tier 4 Prize",
      description: "Staff selects from available Tier 4 items",
      pointCost: 700,
      quantity: 999,
      requiresAdmin: true,
    },
    {
      name: "Nintendo Switch game",
      pointCost: 300,
      quantity: 999,
      requiresAdmin: true,
    },
    { name: "Tablet", pointCost: 700, quantity: 999, requiresAdmin: true },
    {
      name: "Nintendo Switch",
      pointCost: 800,
      quantity: 1,
      requiresAdmin: true,
    },
    { name: "PS5", pointCost: 1500, quantity: 1, requiresAdmin: true },
    {
      name: "Xbox Series X",
      pointCost: 1500,
      quantity: 1,
      requiresAdmin: true,
    },
  ];

  await prisma.behavior.createMany({
    data: behaviors.map((b) => ({ ...b, organizationId })),
  });

  await prisma.prize.createMany({
    data: prizes.map((p) => ({ ...p, organizationId })),
  });
}
